name: flutter_sketch_util_core
description: Utilities for generative art in plain Dart.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
